### PR TITLE
Fixed NoMethod error when querying with an instance of IPAddr

### LINKED ISSUE #1673: Does not work with IPAddr (since 1.8.4)
### Expected behavior

Geocoder should handle instances of `IPAddr` (used for database columns with type `inet`) - like mentioned in #1513.

After upgrading to 1.8.4 this does not work anymore. 
This regression was caused by fixing #1662 with 95eeaba15714ff57052abc89f2c54a3415fa6139.

### Actual behavior

The `sanitized_text` method tries to call `IPAddr#strip`, which does not exist:
https://github.com/alexreisner/geocoder/blob/v1.8.4/lib/geocoder/query.rb#L26

### Steps to reproduce

```
myapp(dev)> Geocoder::Query.new(IPAddr.new "1.1.1.1").sanitized_text
(myapp):8:in `<main>': undefined method `strip' for an instance of IPAddr (NoMethodError)

        text.strip
            ^^^^^^
```

This patch allows using `1.8.4` in my app:

```ruby
IPAddr.class_eval do 
  delegate :strip, to: :to_s
end
```

### Environment info

* Geocoder version: 1.8.4
* Rails version: 8
* Database (if applicable): 
* Lookup (if applicable): ipdata_co

### PR DESCRIPTION
**Pull request by mattlemx**
fixes #1673

### CODE REVIEW

**Comment by alexreisner** [comment]
Perfect, thanks!
