### ISSUE TITLE
request.location is nil in 1.3.5

### ISSUE THREAD

**Issue by lmirosevic** [alexreisner/geocoder#1060]
Accessing the `request.location` object from a Sinatra GET handler (which returns a Sinatra::Request, which inherits from Rack::Request), throws an error.

This works fine in `1.3.4`

```
11:22:55 web.1  | 2016-05-30 11:22:55 - NoMethodError - undefined method `location' for #<Sinatra::Request:0x007ff32e027f78>:
```

**Comment by alexreisner** [comment]
Thanks! And sorry about that. This was caused by #1041. The fix should be simple.

**Comment by alexreisner** [comment]
Just released 1.3.6, which should fix this.

**Comment by lmirosevic** [comment]
Awesome, thanks!
